version: '3.8'

services:
  frontend:
    build:
      context: ./Everyday-Elegance
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./ecommerce-backend
    ports:
      - "1337:1337"
    volumes:
      - strapi-uploads:/app/public/uploads
    env_file:
      - ./ecommerce-backend/.env
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  strapi-uploads:
  db-data:


networks:
  app-network:
    driver: bridge
